default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres # PostgreSQL kullanıcı adın
  password: buss00 # Kurulumda belirlediğin şifre
  pool: 5

development:
  <<: *default
  database: sdp_api_development

test:
  <<: *default
  database: sdp_api_test

production:
  <<: *default
  database: sdp_api_production
  username: sdp_api
  password: <%= ENV['SDP_API_DATABASE_PASSWORD'] %>
